import type { UrdfSummary } from './types';
import { buildParentMap, findLeafLinks, findRootLinks, walkChainJoints } from './chainUtils';

export interface GroupSpec {
  name: string;
  baseLink: string;
  tipLink: string;
}

/** Renders a number as a YAML float literal (never a bare integer) — see the jointlimits-int-literal check. */
function toFloatLiteral(n: number): string {
  return Number.isInteger(n) ? `${n}.0` : `${n}`;
}

function groupNameFromLeaf(leaf: string, index: number): string {
  const stripped = leaf.replace(/^link_/i, '').replace(/_link$/i, '').replace(/^link$/i, '');
  return stripped || `group${index + 1}`;
}

function buildChildrenMap(urdf: UrdfSummary): Map<string, string[]> {
  const map = new Map<string, string[]>();
  urdf.joints.forEach((j) => {
    if (!j.parentLink || !j.childLink) return;
    if (!map.has(j.parentLink)) map.set(j.parentLink, []);
    map.get(j.parentLink)!.push(j.childLink);
  });
  return map;
}

/**
 * Picks a reasonable default set of planning groups with no user input, so a one-click
 * "generate everything" flow has something sensible to work from:
 *  - a single-chain URDF (one leaf) becomes one "arm" group, root to that leaf.
 *  - a branching URDF (e.g. an arm ending in a 2-finger gripper) walks the single-child
 *    "trunk" from the root to the first branch point, makes that the "arm" group, and adds
 *    one small group per leaf from the branch point onward (so a gripper's fingers don't
 *    each drag the whole arm's joints in with them).
 * Still just a starting guess — editable afterwards, not a substitute for picking real
 * planning groups by hand.
 */
export function autoDetectGroups(urdf: UrdfSummary): GroupSpec[] {
  const roots = findRootLinks(urdf);
  const leaves = findLeafLinks(urdf);
  if (roots.length === 0 || leaves.length === 0) return [];
  const root = roots[0];

  if (leaves.length === 1) {
    return leaves[0] === root ? [] : [{ name: 'arm', baseLink: root, tipLink: leaves[0] }];
  }

  const childrenMap = buildChildrenMap(urdf);
  let branchPoint = root;
  while ((childrenMap.get(branchPoint) ?? []).length === 1) {
    branchPoint = childrenMap.get(branchPoint)![0];
  }

  const groups: GroupSpec[] = [];
  if (branchPoint !== root) groups.push({ name: 'arm', baseLink: root, tipLink: branchPoint });
  leaves
    .filter((leaf) => leaf !== branchPoint)
    .forEach((leaf, i) => groups.push({ name: groupNameFromLeaf(leaf, i), baseLink: branchPoint, tipLink: leaf }));
  return groups;
}

function actuatedJointNames(urdf: UrdfSummary, joints: string[]): string[] {
  const byName = new Map(urdf.joints.map((j) => [j.name, j]));
  return joints.filter((name) => {
    const j = byName.get(name);
    return !!j && j.type !== 'fixed' && !j.mimic;
  });
}

/**
 * Generates a starting SRDF + joint_limits.yaml + moveit_controllers.yaml from a URDF and a
 * set of user-chosen planning-group chains — for people who haven't run (or don't want to
 * install) MoveIt Setup Assistant yet. Schema matches real Setup-Assistant output, verified
 * earlier against moveit/moveit_resources' panda_moveit_config.
 *
 * This is a reasonable *starting point*, not a full replacement for Setup Assistant: it can't
 * compute the actual self-collision matrix (that needs collision geometry sampling), so
 * disable_collisions only covers directly-adjacent link pairs (every joint's parent/child) —
 * the same "Adjacent" pairs Setup Assistant always includes, just not any of the further
 * "Never" pairs it finds by sampling.
 */
export function generateMoveitPackage(urdf: UrdfSummary, robotName: string, groups: GroupSpec[]) {
  const parentMap = buildParentMap(urdf);
  const roots = findRootLinks(urdf);

  const groupChains = groups.map((g) => ({
    ...g,
    ...walkChainJoints(parentMap, g.baseLink, g.tipLink),
  }));

  const srdfLines: string[] = [];
  srdfLines.push('<?xml version="1.0" ?>');
  srdfLines.push('<!--This does not replace URDF, and is not an extension of URDF.');
  srdfLines.push('    This is a format for representing semantic information about the robot structure.');
  srdfLines.push('    Generated by RoboticsTools.in\'s MoveIt Configuration Helper as a starting point —');
  srdfLines.push('    review it (especially disable_collisions) before relying on it.-->');
  srdfLines.push(`<robot name="${robotName}">`);

  groupChains.forEach((g) => {
    srdfLines.push(`    <group name="${g.name}">`);
    srdfLines.push(`        <chain base_link="${g.baseLink}" tip_link="${g.tipLink}"/>`);
    srdfLines.push('    </group>');
  });

  if (roots.length === 1) {
    srdfLines.push(`    <virtual_joint name="virtual_joint" type="fixed" parent_frame="world" child_link="${roots[0]}"/>`);
  }

  const adjacentPairs = new Set<string>();
  urdf.joints.forEach((j) => {
    if (!j.parentLink || !j.childLink) return;
    const key = [j.parentLink, j.childLink].sort().join('|');
    if (adjacentPairs.has(key)) return;
    adjacentPairs.add(key);
    srdfLines.push(`    <disable_collisions link1="${j.parentLink}" link2="${j.childLink}" reason="Adjacent"/>`);
  });

  srdfLines.push('</robot>');
  const srdf = srdfLines.join('\n') + '\n';

  const allActuated = actuatedJointNames(
    urdf,
    urdf.joints.map((j) => j.name),
  );
  const jointLimitsLines: string[] = [
    '# Generated by RoboticsTools.in\'s MoveIt Configuration Helper as a starting point.',
    '# max_acceleration is a placeholder (0.3 rad/s^2) — tune it for your actuators.',
    'joint_limits:',
  ];
  allActuated.forEach((name) => {
    const j = urdf.joints.find((x) => x.name === name)!;
    const maxVelocity = j.limitVelocity ?? 1.0;
    jointLimitsLines.push(`  ${name}:`);
    jointLimitsLines.push('    has_velocity_limits: true');
    jointLimitsLines.push(`    max_velocity: ${toFloatLiteral(maxVelocity)}`);
    jointLimitsLines.push('    has_acceleration_limits: true');
    jointLimitsLines.push('    max_acceleration: 0.3');
  });
  const jointLimits = jointLimitsLines.join('\n') + '\n';

  // Schema verified against a real Setup-Assistant-generated file, moveit/moveit_resources
  // (ros2 branch) panda_moveit_config/config/moveit_controllers.yaml — MoveIt2 uses this
  // nested moveit_simple_controller_manager shape, not the flat ROS1-style controller_list.
  const namedGroupControllers = groupChains
    .map((g) => ({ name: `${g.name}_controller`, joints: actuatedJointNames(urdf, [...g.joints].reverse()) }))
    .filter((c) => c.joints.length > 0);

  const controllersLines: string[] = [
    'moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager',
    '',
    'moveit_simple_controller_manager:',
    '  controller_names:',
    ...namedGroupControllers.map((c) => `    - ${c.name}`),
    '',
  ];
  namedGroupControllers.forEach((c) => {
    controllersLines.push(`  ${c.name}:`);
    controllersLines.push('    action_ns: follow_joint_trajectory');
    controllersLines.push('    type: FollowJointTrajectory');
    controllersLines.push('    default: true');
    controllersLines.push('    joints:');
    c.joints.forEach((j) => controllersLines.push(`      - ${j}`));
  });
  const controllers = controllersLines.join('\n') + '\n';

  // kinematics.yaml — defaults verified against panda_moveit_config/config/kinematics.yaml.
  const kinematicsLines: string[] = [];
  groupChains.forEach((g) => {
    kinematicsLines.push(`${g.name}:`);
    kinematicsLines.push('  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin');
    kinematicsLines.push('  kinematics_solver_search_resolution: 0.005');
    kinematicsLines.push('  kinematics_solver_timeout: 0.05');
  });
  const kinematics = kinematicsLines.join('\n') + '\n';

  // initial_positions.yaml — every actuated joint defaults to 0.0. That's not guaranteed to
  // be inside every joint's <limit> range, so this is a starting point to sanity-check, not
  // a guaranteed-valid pose.
  const uniqueActuatedJoints = [...new Set(groupChains.flatMap((g) => actuatedJointNames(urdf, [...g.joints].reverse())))];
  const initialPositionsLines: string[] = [
    '# All-zero starting point — not guaranteed to be inside every joint\'s <limit> range.',
    '# Review against your URDF before relying on it as a fake-hardware start pose.',
    'initial_positions:',
    ...uniqueActuatedJoints.map((j) => `  ${j}: 0.0`),
  ];
  const initialPositions = initialPositionsLines.join('\n') + '\n';

  // ros2_controllers.yaml — schema verified against panda_moveit_config/config/ros2_controllers.yaml.
  const ros2ControllersLines: string[] = [
    'controller_manager:',
    '  ros__parameters:',
    '    update_rate: 100  # Hz',
    '',
    '    joint_state_broadcaster:',
    '      type: joint_state_broadcaster/JointStateBroadcaster',
    ...groupChains.flatMap((g) => [`    ${g.name}_controller:`, '      type: joint_trajectory_controller/JointTrajectoryController']),
    '',
  ];
  groupChains.forEach((g) => {
    const joints = actuatedJointNames(urdf, [...g.joints].reverse());
    if (joints.length === 0) return;
    ros2ControllersLines.push(`${g.name}_controller:`);
    ros2ControllersLines.push('  ros__parameters:');
    ros2ControllersLines.push('    joints:');
    joints.forEach((j) => ros2ControllersLines.push(`      - ${j}`));
    ros2ControllersLines.push('    command_interfaces:');
    ros2ControllersLines.push('      - position');
    ros2ControllersLines.push('    state_interfaces:');
    ros2ControllersLines.push('      - position');
    ros2ControllersLines.push('      - velocity');
    ros2ControllersLines.push('');
  });
  const ros2Controllers = ros2ControllersLines.join('\n') + '\n';

  return { srdf, jointLimits, controllers, kinematics, initialPositions, ros2Controllers };
}
