import type { UrdfSummary } from './types';
import { buildParentMap, findRootLinks, walkChainJoints } from './chainUtils';

export interface GroupSpec {
  name: string;
  baseLink: string;
  tipLink: string;
}

/** Renders a number as a YAML float literal (never a bare integer) — see the jointlimits-int-literal check. */
function toFloatLiteral(n: number): string {
  return Number.isInteger(n) ? `${n}.0` : `${n}`;
}

function actuatedJointNames(urdf: UrdfSummary, joints: string[]): string[] {
  const byName = new Map(urdf.joints.map((j) => [j.name, j]));
  return joints.filter((name) => {
    const j = byName.get(name);
    return !!j && j.type !== 'fixed' && !j.mimic;
  });
}

/**
 * Generates a starting SRDF + joint_limits.yaml + moveit_controllers.yaml from a URDF and a
 * set of user-chosen planning-group chains — for people who haven't run (or don't want to
 * install) MoveIt Setup Assistant yet. Schema matches real Setup-Assistant output, verified
 * earlier against moveit/moveit_resources' panda_moveit_config.
 *
 * This is a reasonable *starting point*, not a full replacement for Setup Assistant: it can't
 * compute the actual self-collision matrix (that needs collision geometry sampling), so
 * disable_collisions only covers directly-adjacent link pairs (every joint's parent/child) —
 * the same "Adjacent" pairs Setup Assistant always includes, just not any of the further
 * "Never" pairs it finds by sampling.
 */
export function generateMoveitPackage(urdf: UrdfSummary, robotName: string, groups: GroupSpec[]) {
  const parentMap = buildParentMap(urdf);
  const roots = findRootLinks(urdf);

  const groupChains = groups.map((g) => ({
    ...g,
    ...walkChainJoints(parentMap, g.baseLink, g.tipLink),
  }));

  const srdfLines: string[] = [];
  srdfLines.push('<?xml version="1.0" ?>');
  srdfLines.push('<!--This does not replace URDF, and is not an extension of URDF.');
  srdfLines.push('    This is a format for representing semantic information about the robot structure.');
  srdfLines.push('    Generated by RoboticsTools.in\'s MoveIt Configuration Helper as a starting point —');
  srdfLines.push('    review it (especially disable_collisions) before relying on it.-->');
  srdfLines.push(`<robot name="${robotName}">`);

  groupChains.forEach((g) => {
    srdfLines.push(`    <group name="${g.name}">`);
    srdfLines.push(`        <chain base_link="${g.baseLink}" tip_link="${g.tipLink}"/>`);
    srdfLines.push('    </group>');
  });

  if (roots.length === 1) {
    srdfLines.push(`    <virtual_joint name="virtual_joint" type="fixed" parent_frame="world" child_link="${roots[0]}"/>`);
  }

  const adjacentPairs = new Set<string>();
  urdf.joints.forEach((j) => {
    if (!j.parentLink || !j.childLink) return;
    const key = [j.parentLink, j.childLink].sort().join('|');
    if (adjacentPairs.has(key)) return;
    adjacentPairs.add(key);
    srdfLines.push(`    <disable_collisions link1="${j.parentLink}" link2="${j.childLink}" reason="Adjacent"/>`);
  });

  srdfLines.push('</robot>');
  const srdf = srdfLines.join('\n') + '\n';

  const allActuated = actuatedJointNames(
    urdf,
    urdf.joints.map((j) => j.name),
  );
  const jointLimitsLines: string[] = [
    '# Generated by RoboticsTools.in\'s MoveIt Configuration Helper as a starting point.',
    '# max_acceleration is a placeholder (0.3 rad/s^2) — tune it for your actuators.',
    'joint_limits:',
  ];
  allActuated.forEach((name) => {
    const j = urdf.joints.find((x) => x.name === name)!;
    const maxVelocity = j.limitVelocity ?? 1.0;
    jointLimitsLines.push(`  ${name}:`);
    jointLimitsLines.push('    has_velocity_limits: true');
    jointLimitsLines.push(`    max_velocity: ${toFloatLiteral(maxVelocity)}`);
    jointLimitsLines.push('    has_acceleration_limits: true');
    jointLimitsLines.push('    max_acceleration: 0.3');
  });
  const jointLimits = jointLimitsLines.join('\n') + '\n';

  const controllersLines: string[] = ['controller_list:'];
  groupChains.forEach((g) => {
    // g.joints is collected walking tip -> base; reverse to the more natural base -> tip order.
    const joints = actuatedJointNames(urdf, [...g.joints].reverse());
    if (joints.length === 0) return;
    controllersLines.push(`  - name: ${g.name}_controller`);
    controllersLines.push('    action_ns: follow_joint_trajectory');
    controllersLines.push('    type: FollowJointTrajectory');
    controllersLines.push('    joints:');
    joints.forEach((j) => controllersLines.push(`      - ${j}`));
  });
  const controllers = controllersLines.join('\n') + '\n';

  return { srdf, jointLimits, controllers };
}
