import type { JointLimitEntry, JointLimitNumericValue, JointLimitsFile } from './types';

function parseNumeric(raw: string): JointLimitNumericValue | null {
  const trimmed = raw.trim();
  const num = parseFloat(trimmed);
  if (Number.isNaN(num)) return null;
  return { raw: trimmed, num, isIntLiteral: /^-?\d+$/.test(trimmed) };
}

/**
 * Minimal parser for joint_limits.yaml, e.g. as generated by MoveIt Setup Assistant
 * (verified against moveit/moveit_resources panda_moveit_config/config/joint_limits.yaml):
 *
 * joint_limits:
 *   panda_joint1:
 *     has_velocity_limits: true
 *     max_velocity: 2.175
 *     has_acceleration_limits: true
 *     max_acceleration: 3.75
 *
 * Only handles this flat two-level shape (top key `joint_limits:`, then one level of
 * per-joint keys, then scalar leaf values) — enough to cross-check joint names and value
 * formatting, not a general YAML parser.
 */
export function parseJointLimitsYaml(text: string): JointLimitsFile {
  const lines = text.split('\n');
  const entries: JointLimitEntry[] = [];

  let inJointLimits = false;
  let current: JointLimitEntry | null = null;

  const indentOf = (line: string) => line.length - line.trimStart().length;

  for (const raw of lines) {
    const line = raw.replace(/#.*$/, '').replace(/\r$/, '');
    if (!line.trim()) continue;
    const indent = indentOf(line);
    const trimmed = line.trim();

    if (indent === 0) {
      if (/^joint_limits:\s*$/.test(trimmed)) {
        inJointLimits = true;
        current = null;
      } else {
        inJointLimits = false;
        current = null;
      }
      continue;
    }

    if (!inJointLimits) continue;

    const jointHeaderMatch = /^([A-Za-z0-9_]+):\s*$/.exec(trimmed);
    if (indent === 2 && jointHeaderMatch) {
      current = { jointName: jointHeaderMatch[1], allNumericValues: {} };
      entries.push(current);
      continue;
    }

    if (indent >= 4 && current) {
      const kv = /^([A-Za-z0-9_]+):\s*(.+)$/.exec(trimmed);
      if (!kv) continue;
      const [, key, rawValue] = kv;
      const value = rawValue.trim();
      if (key === 'has_velocity_limits') {
        current.hasVelocityLimits = value === 'true';
      } else if (key === 'has_acceleration_limits') {
        current.hasAccelerationLimits = value === 'true';
      } else {
        const numeric = parseNumeric(value);
        if (numeric) {
          current.allNumericValues[key] = numeric;
          if (key === 'max_velocity') current.maxVelocity = numeric;
          else if (key === 'max_acceleration') current.maxAcceleration = numeric;
        }
      }
    }
  }

  if (entries.length === 0 && !/joint_limits:/.test(text)) {
    return { entries: [], parseError: 'No top-level "joint_limits:" key found — this doesn\'t look like a joint_limits.yaml file.' };
  }

  return { entries, parseError: null };
}
